name: ventparliament
dependencies:
  - python>=3.7
  - cython
  - ipython
  - numpy
  - pandas
  - seaborn
  - scipy=1.4.1
  - pathlib
  - matplotlib
  - pyqt
  - jupyter
  - pip
  - scikit-learn
  - pip:
    - git+git://github.com/lukauskas/dtwco.git#egg=dtwco
    - beautifulsoup4
    - colorcet
    - git+https://github.com/hahnicity/fuzzy-clustering.git
    - prettytable
    - ventmap>=1.4.7
    - nose
channels:
  - conda-forge
