name: parliament
dependencies:
  - python>=3.7
  - cython
  - ipython
  - numpy
  - pandas
  - seaborn
  - scipy=1.4.1
  - pathlib
  - matplotlib
  - pyqt
  - jupyter
  - pip
  - pip:
    - colorcet
    - git+https://github.com/hahnicity/fuzzy-clustering.git
    - prettytable
    - statsmodels
    - ventmap>=1.4.7
channels:
  - conda-forge
